
spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        #        enable_lazy_load_no_trans: true
        format_sql: true
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
  jmx:
    default-domain: api.pallycon.com
    enabled: false
  application:
    name: PallyConBillngAPI
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      time-between-eviction-runs-millis: 7200000
      test-while-idle: true
      validation-query: SELECT 1
      connection-test-query: SELECT 1
      validation-interval: 0
      test-on-borrow: true
      maxIdle: 20
      maxActive: 400
      maxWait: 10000
      default-auto-commit: true

server:
  port: 80
  compression:
    enabled: false
  connection-timeout: 3000
  tomcat:
    max-threads: 300

tomcat:
  ajp:
    protocol: AJP/1.3
    port: 8009
    enabled: true

---
spring:
  profiles: local

datasource:
  master: jdbc:mariadb://localhost:3306/dev?autoReconnect=true
  slave: jdbc:mariadb://localhost:3306/dev?autoReconnect=true
  username: test
  password: test
---
spring:
  profiles: dev

datasource:
  master: jdbc:mariadb://localhost:3306/dev?autoReconnect=true
  slave: jdbc:mariadb://localhost:3306/dev?autoReconnect=true
  username: test
  password: test

admin:
  group-seq: 999999999

server:
  port: 84
  compression:
    enabled: false
  connection-timeout: 3000
  tomcat:
    max-threads: 300

tomcat:
  ajp:
    protocol: AJP/1.3
    port: 8109
    enabled: true

---
spring:
  profiles: dev-local

datasource:
  master: jdbc:mariadb://localhost:3306/dev?autoReconnect=true
  slave: jdbc:mariadb://localhost:3306/dev?autoReconnect=true
  username: test
  password: test

server:
  port: 81
  compression:
    enabled: false
  connection-timeout: 3000
  tomcat:
    max-threads: 300

tomcat:
  ajp:
    protocol: AJP/1.3
    port: 8109
    enabled: true

admin:
  group-seq: 999999999

---
spring:
  profiles: server

datasource:
  master: jdbc:mariadb:aurora://pallycon-aurora-cluster.cluster-czwzfdgbx4m4.ap-northeast-2.rds.amazonaws.com:3306/backend?autoReconnect=true
  slave: jdbc:mariadb://pallycon-aurora-cluster.cluster-ro-czwzfdgbx4m4.ap-northeast-2.rds.amazonaws.com:3306/backend?autoReconnect=true
  username: pallycon
  password: pallycon@#admin

admin:
  group-seq: 999
